# Generated by Django 5.0.7 on 2024-07-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='carbohydrates',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='protein',
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_type',
            field=models.CharField(choices=[('carbohydrates', 'Carbohydrates'), ('protein', 'Protein'), ('fat', 'Fat')], default='carbohydrates', max_length=20),
        ),
    ]
