# Generated by Django 5.0.7 on 2024-07-29 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_remove_recipe_carbohydrates_remove_recipe_fat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories', models.FloatField()),
                ('carbs', models.FloatField()),
                ('protein', models.FloatField()),
                ('fat', models.FloatField()),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.RemoveField(
            model_name='usernutrientintake',
            name='user',
        ),
        migrations.AddField(
            model_name='consumption',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.food'),
        ),
        migrations.DeleteModel(
            name='RecommendedNutrientIntake',
        ),
        migrations.DeleteModel(
            name='UserNutrientIntake',
        ),
    ]
